---
title: "Homework2"
author: "Muriel Pokol"
date: "September 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
```


## Map with Points
```{r, markers}
city_temp <- read.csv("CitiesExt.csv")



pal <- colorNumeric(
  palette = "Purples",
  domain = city_temp$temperature)

leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addCircleMarkers(data = city_temp, lng = ~longitude, lat = ~latitude, radius = 1.5, color =  ~pal(temperature)) %>%
  addLegend(position = "topright" , pal = pal, values = city_temp$temperature, title = "temperature?")

```



```{r, loading}
railway_data <- readOGR("./GBR_rails.shp", GDAL1_integer64_policy = TRUE)

leaflet(data = railway_data) %>%  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE), group="WorldTerrain") %>%
  addProviderTiles("OpenStreetMap.HOT", group = "StreetMap") %>%  
  addPolylines(color = "#63CBD3") %>%


  # Layers control
  addLayersControl(
    baseGroups = c("WorldTerrain", "StreetMap"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

```{r, yeet}
admin_data <- readOGR("./GBR_adm2.shp", GDAL1_integer64_policy = TRUE)

leaflet(data = admin_data) %>%  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(color = "blue")
```


